export const FETCH_QUESTIONS_REQUEST = 'FETCH_QUESTIONS_REQUEST';
export const FETCH_QUESTIONS_FUFILLED = 'FETCH_QUESTIONS_FUFILLED';
export const FETCH_QUESTIONS_REJECTED = 'FETCH_QUESTIONS_REJECTED';
export const STORE_QUESTIONS = 'STORE_QUESTIONS';
export const RESET_DATA = 'RESET_DATA';
export const STORE_ANSWER = 'STORE_ANSWER';